const roasts = [
  "You're the reason Wi-Fi cuts out when it rains.",
  "You're not stupid; you just have bad luck thinking.",
  "Your confidence is inspiring—for someone so consistently wrong.",
  "You bring people together… just to talk about you when you leave.",
  "You're like a software update: never wanted, always annoying.",
  "You're the human version of a typo.",
  "You're proof that evolution sometimes takes a break.",
  "You have something on your chin… no, the third one down.",
  "You're like a puzzle with half the pieces missing.",
  "You could be replaced by a rubber duck and no one would notice.",
  "You're not completely useless—you can always serve as a bad example.",
  "Your secrets are safe with everyone. Nobody listens to you.",
  "You're like a broken pencil: pointless.",
  "If you were any slower, you’d be moving backward in time.",
  "You're not the sharpest tool in the shed… or the brightest light… or the fastest processor.",
  "You’re living proof that natural selection has loopholes.",
  "You're the kind of person who claps when the plane lands.",
  "If you had a dollar for every smart thing you said, you’d be broke.",
  "You're the 'before' picture in every ad campaign.",
  "You're not ugly—you’re just… hard to look at.",
  "You're like a software bug that deletes itself and still breaks everything.",
  "You have something special. It’s called mediocrity.",
  "If being annoying was a career, you’d be CEO.",
  "You're the reason the mute button exists.",
  "Your IQ test came back negative.",
  "You're not aging like fine wine. More like milk.",
  "You have something that most people don’t: the ability to talk without saying anything.",
  "You're like a loading bar stuck at 99%.",
  "You're more disappointing than a low battery at 2% with no charger.",
  "You're the kind of person who'd trip over a wireless connection.",
  "You should wear a sign that says 'Caution: Contents underwhelming.'",
  "You bring a lot of joy—mostly when you’re not around.",
  "You're about as useful as an expired antivirus subscription.",
  "You're the reason autocorrect gives up.",
  "You have a face for radio and a voice for silent film.",
  "You're like a fortune cookie with no fortune—empty and crumbly.",
  "You redefine the limits of average.",
  "You're not annoying; you're just persistently unlikable.",
  "You're like a broken link—everyone regrets clicking on you.",
  "You have something rare: the talent to kill conversations instantly.",
  "You're the emoji people avoid using.",
  "You're the soundtrack to a bad decision.",
  "You're more awkward than a Zoom call with no audio.",
  "You're what happens when you microwave metal thoughts.",
  "You're the kind of person who'd lose at hide and seek with GPS.",
  "You're like a pop-up ad that talks back.",
  "You're the Wi-Fi in a remote cabin—promised, but never delivered.",
  "You bring people together… to silently question their life choices.",
  "You're like an elevator to the basement. Nobody wants that ride.",
  "You have a great future… in buffering.",
  "You’re not the main character. You’re not even in the intro.",
  "You're the rerun everyone changes the channel on.",
  // … and 100 more coming up!
];
